/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario.gui;

import horario.dto.Hora;
import horario.gui.tablemodel.TableModelHoras;
import java.util.List;
import horario.logica.LogicaNegocio;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class VentanaLog extends javax.swing.JDialog {

    private VentanaPrincipal padre;

    /**
     * Creates new form JDialogLista
     */
    public VentanaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (VentanaPrincipal) parent;
        jTableLista.setModel(new TableModelHoras(LogicaNegocio.getListaHoras())); //creamos el objeto pasandole al constructor la lista de horas de la clase logicaNegocio        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTADO LOG");

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobleClick(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLista);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dobleClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobleClick
        //si hacemos dobleclic con el botón 1 del ratón
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            int valor = JOptionPane.showConfirmDialog(this, "¿Desea borrar el registro", "Confirmación", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (valor == 0) {
                int fila;
                fila = jTableLista.getSelectedRow();
                TableModelHoras ctm = (TableModelHoras) jTableLista.getModel(); //recuperamos su TableModel
                ctm.deleteRow(fila);
                padre.refrescarHorario();
            }
        }
    }//GEN-LAST:event_dobleClick

    //Método que refresca la tabla
//    private void refrescaTabla(){
//        TableModelHoras ctm = (TableModelHoras) jTableLista.getModel();  //recupero el TableModel de la tabla
//        ctm.refrescar();  //lanzo su metodo para refrescarlo
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    // End of variables declaration//GEN-END:variables
}
